// <auto-generated />
using System;
using MRecipes.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRecipes.Api.Migrations
{
    [DbContext(typeof(MRecipesDbContext))]
    [Migration("20240508202716_HashSaltPw")]
    partial class HashSaltPw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MRecipes.Api.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Article", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 5, 8, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(786),
                            Description = "Ako tak pozerám do kalendára, Veľká noc je už za rohom! Tentokrát mi začiatok roka ubehol ultra rýchlo a človek sa ani nenazdá a bude tu máj a s ním aj ja - opäť o rok staršia. :D Ale nebudem predbiehať, teším sa na Veľkú noc a naše rodinné nedeľné raňajky. Veľkonočnú pasku, hrudku, vajcia natvrdo, údeniny, cviklu s chrenom a zemiakový šalát. Ale nie vždy musí byť Veľká noc len v tradičnom šate. :) Každý rok do nej pridávam aj nejakú tú novinku, naposledy to bola veľkonočná roláda s malinovým krémom, mrkvové mafiny, či avokádová nátierka s granátovým jablkom. A teraz sa môžu moji najbližší tešiť na výborný olivový hummus! Kombinácia cíceru, sezamovej pasty, cesnaku, citrónovej šťavy a olív Kalamata, je výborným krokom na vykročenie do inej svetovej kuchyne. :) Hummus servírovaný s chrumkavou cibuľkou, olivami, kolieskami uhorky a paradajok, pokvapkaný olivovým olejom - u nás doma sa zjedol rýchlosťou blesku a to nie sme milovníci cíceru. Všetky ingrediencie potrebné na tento recept, nájdete pod jednou strechou v Kauflande. Ak ešte nepoznáte ich značku K-Favourites, odporúčam vyskúšať - ingrediencie sú chuťovo výborné a cena príjemná.",
                            Image = "789",
                            Title = "Olivový hummus"
                        },
                        new
                        {
                            Id = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 5, 7, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(860),
                            Description = "Tento víkend sme zvrtli novú variáciu rizota! Pôvodne som chcela spraviť tekvicové, ale z debničky na mňa \"žmurkali\" voňavé cherry paradajky, takže bolo spontánne rozhodnuté v prospech dnešného receptu na paradajkové rizoto. :) Rizoto je jeden z mojich najobľúbenejších receptov, jeho príprava nie je vôbec zložitá, stačí vám naň zopár ingrediencií a dokážete ho pripraviť na desiatky spôsobov v závislosti od sezóny. Na mojom blogu nájdete recept na hubové, ale i cviklové rizoto a čoskoro pribudnú aj ďalšie, keďže vás chcem naňho namotať :) Rizoto je úžasne krémové, prevoňané pečenými paradajkami s cesnakom a čerstvou bazalkou. Čochvíľa nám začne sezóna paradajok, tie skleníkové si však môžete dopriať už dnes a využiť ich rovno pri testovaní tohto receptu, prípadne odporúčam vyskúšať moju rýchlu paradajkovú polievku, paradajkový džem či mäsové guľky v paradajkovej omáčke. Verím, že si pochutíte!",
                            Image = "012",
                            Title = "Famózne paradajkové rizoto"
                        },
                        new
                        {
                            Id = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 5, 5, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(866),
                            Description = "Blíži sa jar a s ňou aj všetky milé stretnutia s našimi blízkymi. U nás doma som zaviedla tradíciu nedeľných dlhých raňajok a vždy keď máme pred sebou voľný víkend, rada na tieto dlhé raňajky pozývam aj svojich najbližších. Jedlo a konverzácie pri spoločnom stole, ktoré ho sprevádzajú, sú pre mňa jedny z najmilších okamihov, preto rada vymýšľam vždy nové a nové kombinácie jedál, ktorými by som ich pohostila. :) A najradšej sa inšpirujem práve v talianskej kuchyni, keďže tá je známa svojou jednoduchosťou, kvalitnými ingredienciami a pritom zaručene chutným výsledkom. Mnohí z vás už určite poznajú recept na chrumkavú paradajkovú bruschettu, ktorú nájdete v mojej prvej kuchárskej knihe. Tento recept je jej malou obmenou, je však vhodný pre všetkých bezlepkáčov, nakoľko v ňom nájdete aj tip na bezgluténové pečivo od Kauflandu. V ich sortimente nájdete pod značkou K-free bezgluténové pečivo a cestoviny, ktoré rada využívam pri príprave bezlepkových receptov. Na chrumkavú bruschettu vám stačí zopár ingrediencií a výsledok je neuveriteľne chutný! Budem sa tešiť, ak recept najbližšie vyskúšate a dáte mi vedieť, ako vám chutilo.",
                            Image = "345",
                            Title = "Chrumkavá paradajková bruschetta"
                        },
                        new
                        {
                            Id = new Guid("4c26d85b-3146-4ed2-9f2c-3993e02ee888"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 5, 1, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(870),
                            Description = "popis",
                            Image = "567",
                            Title = "Zeleninový tart z lístkového cesta"
                        },
                        new
                        {
                            Id = new Guid("2e30dc7c-0c1f-4438-9a3e-3f47792fc82d"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 28, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(873),
                            Description = "popis",
                            Image = "890",
                            Title = "Jednoduchý grécky šalát"
                        },
                        new
                        {
                            Id = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 26, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(876),
                            Description = "popis",
                            Image = "123",
                            Title = "Arašidové brownies s malinami"
                        },
                        new
                        {
                            Id = new Guid("c2902ef3-8e41-4f88-b9a3-31981e4ac220"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 24, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(878),
                            Description = "popis",
                            Image = "456",
                            Title = "Paella s morskými plodmi"
                        },
                        new
                        {
                            Id = new Guid("b5e5d3c7-6b28-456e-87ed-d53c10c3f36d"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 24, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(881),
                            Description = "popis",
                            Image = "787",
                            Title = "Tikka Masala"
                        },
                        new
                        {
                            Id = new Guid("90378085-c0de-4c91-a83c-d216d246b2b1"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 21, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(884),
                            Description = "popis",
                            Image = "011",
                            Title = "Čokoládový tart"
                        },
                        new
                        {
                            Id = new Guid("e62c4460-2829-4f20-b747-5ef468d02d17"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 13, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(887),
                            Description = "popis",
                            Image = "341",
                            Title = "Špagety Bolognese"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleComments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5122af55-bafe-4732-b90e-a5c499e7df4b"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            DateAdded = new DateTime(2024, 5, 6, 22, 27, 16, 241, DateTimeKind.Local).AddTicks(914),
                            Description = "mnam do pyska",
                            Name = "jozka"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f5e4a6b-d1bf-495d-a7de-8c5639d26034"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("38b57f79-26ee-4fe5-adcb-01a079cf871f"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            TagId = new Guid("a1b6b079-1c3e-4bb0-8b33-ae6f3dc53e3d")
                        },
                        new
                        {
                            Id = new Guid("9eeb8f4b-3d2c-487e-951d-1f222bf91330"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("4884e6e4-f306-4933-a600-12dd8399afa5"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("0bb9a5d2-1d14-407f-8094-fab3ac34297b"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            TagId = new Guid("b1eac43b-9a2a-4e37-94d2-0a59a493c7d3")
                        },
                        new
                        {
                            Id = new Guid("fa933aae-1da6-4551-9298-4447183d0e25"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("7d919f15-d559-43cc-84cd-e0e624938a7e"),
                            ArticleId = new Guid("4c26d85b-3146-4ed2-9f2c-3993e02ee888"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("af52eff0-d126-4cb1-b69b-a187e9258767"),
                            ArticleId = new Guid("2e30dc7c-0c1f-4438-9a3e-3f47792fc82d"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("17d08354-c0a8-40ce-87ba-c5e2d1cf04a7"),
                            ArticleId = new Guid("2e30dc7c-0c1f-4438-9a3e-3f47792fc82d"),
                            TagId = new Guid("c1d698f0-1f87-4c30-9a31-c26e75d99c4f")
                        },
                        new
                        {
                            Id = new Guid("3a7e1f64-e9d4-45c8-8aaf-0974e478d45f"),
                            ArticleId = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            TagId = new Guid("a1f7fd4e-7c7a-4d5b-8a5c-56f5e2d4d18c")
                        },
                        new
                        {
                            Id = new Guid("debb446f-1bbf-4dc5-9d29-81527527e473"),
                            ArticleId = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("c71bcfc4-c04c-4d3f-90ff-cb6d4954d65f"),
                            ArticleId = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            TagId = new Guid("b1f4c4c4-9b64-4aef-9016-4d8a26c44843")
                        },
                        new
                        {
                            Id = new Guid("97b1f5ba-7590-4fd1-b936-f4b63ebee06e"),
                            ArticleId = new Guid("c2902ef3-8e41-4f88-b9a3-31981e4ac220"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("5845bfb1-e7f5-4fe0-ad08-a29c927299e6"),
                            ArticleId = new Guid("c2902ef3-8e41-4f88-b9a3-31981e4ac220"),
                            TagId = new Guid("a1b6b079-1c3e-4bb0-8b33-ae6f3dc53e3d")
                        },
                        new
                        {
                            Id = new Guid("ffdc4e37-2b55-4a95-aee4-6da1ad70a14d"),
                            ArticleId = new Guid("b5e5d3c7-6b28-456e-87ed-d53c10c3f36d"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("1b81005c-79d0-44f9-8027-44308d717570"),
                            ArticleId = new Guid("b5e5d3c7-6b28-456e-87ed-d53c10c3f36d"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("b390c4e1-baf5-464f-bac8-52b2d982e67e"),
                            ArticleId = new Guid("90378085-c0de-4c91-a83c-d216d246b2b1"),
                            TagId = new Guid("a1f7fd4e-7c7a-4d5b-8a5c-56f5e2d4d18c")
                        },
                        new
                        {
                            Id = new Guid("e9f38c7d-5b9d-4376-9acf-dce4b1b33aef"),
                            ArticleId = new Guid("90378085-c0de-4c91-a83c-d216d246b2b1"),
                            TagId = new Guid("b1f4c4c4-9b64-4aef-9016-4d8a26c44843")
                        },
                        new
                        {
                            Id = new Guid("7eb09ff0-0d8c-49d9-b0c8-3438973c00cc"),
                            ArticleId = new Guid("e62c4460-2829-4f20-b747-5ef468d02d17"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("862adb06-6141-4af3-a78f-922904a0c0b8"),
                            ArticleId = new Guid("e62c4460-2829-4f20-b747-5ef468d02d17"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8288271b-5d1a-46fe-a000-9a32a59b2fec"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "250 g predvareného cíceru"
                        },
                        new
                        {
                            Id = new Guid("cf7370a5-0d63-479a-9a27-998a71c44b82"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "60 g sezamovej pasty"
                        },
                        new
                        {
                            Id = new Guid("3951046c-2d71-4fcf-b5ff-e070d6b11636"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "40 g nakrájaných olív Kalamata (ja som použila olivy Kalamata K-Favourites, ktoré nájdete v Kauflande)"
                        },
                        new
                        {
                            Id = new Guid("96e7758f-9a3b-4393-bbf8-721d47d66a39"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "25 ml šťavy z citróna"
                        },
                        new
                        {
                            Id = new Guid("68e0d2dd-56f1-4c38-98d0-02d5b0570f9d"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "1 - 2 strúčiky cesnaku"
                        },
                        new
                        {
                            Id = new Guid("893e2fe5-f098-46e9-91e0-857d2471d1f8"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "2 PL studenej vody'"
                        },
                        new
                        {
                            Id = new Guid("2373b6b5-afeb-4ab7-9ada-be7f466a09b8"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "1 PL panenského olivového oleja"
                        },
                        new
                        {
                            Id = new Guid("39ab9159-abe3-4792-b31c-fbace56a855e"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "1/2 ČL rímskej rasce"
                        },
                        new
                        {
                            Id = new Guid("0742c703-8c42-4e34-b6e6-6dd01df48774"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "soľ a čierne korenie"
                        },
                        new
                        {
                            Id = new Guid("394eef94-6343-4ac6-9f18-25a519d690bb"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "300 g ryže arborio"
                        },
                        new
                        {
                            Id = new Guid("89b3f6eb-5ee6-4e0d-b9b9-6111dad9940c"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "1 cibuľa"
                        },
                        new
                        {
                            Id = new Guid("39bed748-79a6-4c61-8d56-f3ebc4ace01c"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "200 ml bieleho suchého vína"
                        },
                        new
                        {
                            Id = new Guid("b1d44cad-0583-4c01-9946-3bf0b219112c"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "300 ml paradajkového pretlaku/passaty"
                        },
                        new
                        {
                            Id = new Guid("7e75b035-c3c1-4021-ba02-97540f6d871d"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "700 ml vývaru/vody"
                        },
                        new
                        {
                            Id = new Guid("31e28653-c92c-4403-a6c4-9213cc9589c5"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "3 plátky masla"
                        },
                        new
                        {
                            Id = new Guid("97280559-e326-4cfc-8977-f23dd618feeb"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "100 g parmezánu"
                        },
                        new
                        {
                            Id = new Guid("5e62e578-8abb-43ac-b993-c16f750e4860"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "panenský olivový olej"
                        },
                        new
                        {
                            Id = new Guid("89a106c3-bf3b-45dd-bc14-854aacb6316d"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "soľ a čierne korenie"
                        },
                        new
                        {
                            Id = new Guid("7c5eea18-a915-402b-9308-aa9e980f58f6"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "sušená bazalka"
                        },
                        new
                        {
                            Id = new Guid("d88a768b-087f-4fb4-8962-c39be818624e"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "sušené oregano"
                        },
                        new
                        {
                            Id = new Guid("098aae72-87fa-43f4-9f4a-dae261c406b3"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "hrsť čerstvej bazalky"
                        },
                        new
                        {
                            Id = new Guid("d151d926-347c-472f-a2c9-14868fade684"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "500 g cherry paradajok"
                        },
                        new
                        {
                            Id = new Guid("43df8e97-f94e-4280-8146-1e1daaab51dc"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "4 strúčiky cesnaku"
                        },
                        new
                        {
                            Id = new Guid("a78a2471-3330-4914-a17a-1ad003655129"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "500 g cherry paradajok"
                        },
                        new
                        {
                            Id = new Guid("867e72b4-461d-46c9-a13c-e519a261bd45"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "7 PL panenského olivového oleja"
                        },
                        new
                        {
                            Id = new Guid("b712f41b-91d1-4780-9ca6-4cce444ac34d"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "3 strúčiky cesnaku"
                        },
                        new
                        {
                            Id = new Guid("d783930d-939e-49e7-958b-20f1c348622a"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "1 bageta alebo iné pečivo (pre verziu bez lepku odporúčam použiť 1 balenie bezlepkových svetlých žemlí K-free, ktoré nájdete v Kauflande)"
                        },
                        new
                        {
                            Id = new Guid("42dbfac8-30b2-4021-a65a-277e1d8c690c"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "mozzarella"
                        },
                        new
                        {
                            Id = new Guid("06533be1-7c0b-4657-b7f2-5b49d7b47e6a"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "bazalkové pesto"
                        },
                        new
                        {
                            Id = new Guid("5a8583fd-4930-4118-a89b-bf2e08274962"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "hrsť lístkov bazalky"
                        },
                        new
                        {
                            Id = new Guid("b3de39ff-0c53-4d67-8671-2d2f7cbf78e4"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "soľ a čierne korenie"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Step", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a02102c6-8307-4972-b1ef-f238d8f1a0a0"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "Predvarený cícer z konzervy prepláchneme, preložíme do hrnca, zalejeme vodou, jemne osolíme a privedieme do varu. Keď začne vrieť, znížime teplotu a prikrytý varíme približne 20 minút. Mäkký cícer prepláchneme studenou vodou a zbavíme šupiek. Presypeme ho do výkonného mixéra a pridáme k nemu ostatné ingrediencie na hummus. Vymixujeme dohladka a v prípade potreby pridáme trochu vody. Dochutíme soľou, čiernym korením a citrónovou šťavou."
                        },
                        new
                        {
                            Id = new Guid("b459ad6f-37b2-4cef-9b17-cc75cf1da34e"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "Hummus pred podávaním ochutíme trochou mletej červenej papriky, pokvapkáme olivovým olejom a ozdobíme nakrájanou cibuľou, paradajkami, kolieskami uhorky a hrsťou zelených a čiernych olív. Servírujeme s plátkami citróna, slanými krekrami a výberom rôznych salám a syrov."
                        },
                        new
                        {
                            Id = new Guid("8ce3a103-f2bc-48d2-ab0b-7102e18c80b8"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Paradajky nakrájame na štvrtiny a vložíme do misky. Pokvapkáme ich olivovým olejom (cca 5 PL panenského olivového oleja), pridáme prelisované strúčiky cesnaku a ochutíme soľou a čiernym korením. Premiešame lyžicou a necháme pár minút odležať. Následne celú zmes preložíme na plech vyložený papierom na pečenie a vložíme do rúry vyhriatej na 200 °C. Pečieme 25 minút."
                        },
                        new
                        {
                            Id = new Guid("b540f01c-515d-4e3c-b538-6f1a6ff651a2"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "V menšom hrnci zohrejeme kurací alebo zeleninový vývar. Ak vývar nemáte, môžete použiť aj vodu - do menšieho hrnca dajte zohriať 700 ml vody a keď bude horúca, pridajte do nej lyžičku soli a dobre premiešajte. Vývar, prípadne vodu zohrievame preto, aby mali podobnú teplotu ako ryža. Vďaka tomu sa nezastaví proces varenia a budete mať rizoto presne také, aké má byť - krémové a neskutočne dobré."
                        },
                        new
                        {
                            Id = new Guid("1e844085-08c4-48e1-bf8f-0803e933eb80"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Kým sa vývar/voda zohrieva, zohrejeme si v hlbokej panvici olivový olej, pridáme nadrobno nasekanú cibuľu a opečieme dosklovita. Prisypeme nepremytú ryžu arborio (môžete použiť aj carnaroli ryžu) a poriadne premiešame, aby sa ryža obalila vo vrstve oleja. Opekáme cca 4 minúty, pričom ryžu pravidelne premiešavame. Prilejeme víno a za občasného miešania privedieme do varu. Varíme cca 2 minúty, kým sa víno neodparí."
                        },
                        new
                        {
                            Id = new Guid("1911c3f6-31a5-4bb9-873e-1b84a2ef99d9"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Prilejeme paradajkový pretlak/passatu a dobre premiešame. Znížime teplotu na stredný plameň, pridáme naberačku teplého vývaru alebo osolenej vody a pravidelne miešame, kým sa voda nevstrebe. Pokračujeme v postupnom pridávaní vody a zakaždým premiešavame, kým sa voda nevstrebe a ryža sa neuvarí al dente. Ryža je hotová vtedy, keď je obklopená krémovou tekutinou a po ochutnaní je jemne chrumkavá. Celý proces varenia trvá cca 25 minút."
                        },
                        new
                        {
                            Id = new Guid("8e096b47-83c1-454c-82ee-a99015deb466"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Rizoto stiahneme zo sporáka, pridáme k nemu plátky masla a nastrúhaný parmezán a vareškou jemne premiešame. Podľa potreby dochutíme soľou, čiernym korením, trochou sušeného oregana a bazalky. Rizoto servírujeme v hlbokých tanieroch, navrch dáme pečené paradajky a ozdobíme lístkami čerstvej bazalky. Rizoto podávame hneď po uvarení, vtedy chutí najlepšie, s pohárom bieleho vína priam dokonale!"
                        },
                        new
                        {
                            Id = new Guid("cc46e596-a5b7-4b47-8b29-d925c2c6f37d"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "Paradajky nakrájame na menšie kúsky a vložíme do misky. Zalejeme ich olivovým olejom, pridáme prelisované strúčiky cesnaku, ochutíme soľou a čiernym korením a dobre premiešame. Necháme pár minút postáť. Následne paradajky preložíme na plech vyložený papierom na pečenie a vložíme do rúry vyhriatej na 200 °C. Pečieme približne 30 minút, kým nezmäknú."
                        },
                        new
                        {
                            Id = new Guid("e8f27cbf-ba1f-4380-9308-47e0adf0b8c0"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "Bagetu alebo iné pečivo nakrájame na približne rovnaké kúsky. Ak použijete bezlepkové svetlé žemle K-free od Kauflandu, prekrojte ich na polovicu. Jednotlivé kúsky potrieme zvyšným olivovým olejom, ktorý zostal v miske a opečieme na grile, panvici alebo vložíme na 10 minút do rúry. Chrumkavé pečivo potrieme pestom, na to dáme plátok mozzarelly, grilované paradajky a lístky čerstvej bazalky."
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825"),
                            Name = "Hlavný chod"
                        },
                        new
                        {
                            Id = new Guid("a1f7fd4e-7c7a-4d5b-8a5c-56f5e2d4d18c"),
                            Name = "Dezerty"
                        },
                        new
                        {
                            Id = new Guid("b1eac43b-9a2a-4e37-94d2-0a59a493c7d3"),
                            Name = "Predjedlá"
                        },
                        new
                        {
                            Id = new Guid("c1d698f0-1f87-4c30-9a31-c26e75d99c4f"),
                            Name = "Šaláty"
                        },
                        new
                        {
                            Id = new Guid("d1e13f16-9e32-4d3e-8302-28516d982aef"),
                            Name = "Polievky"
                        },
                        new
                        {
                            Id = new Guid("e13e2d0d-c51f-4fa9-97cb-4e6c018474cb"),
                            Name = "Nápoje"
                        },
                        new
                        {
                            Id = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5"),
                            Name = "Bez lepku"
                        },
                        new
                        {
                            Id = new Guid("a1b6b079-1c3e-4bb0-8b33-ae6f3dc53e3d"),
                            Name = "Bez laktózy"
                        },
                        new
                        {
                            Id = new Guid("b1f4c4c4-9b64-4aef-9016-4d8a26c44843"),
                            Name = "Sladké"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Article", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleComment", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleTag", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MRecipes.Api.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Ingredient", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Ingredients")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Step", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Steps")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
