// <auto-generated />
using System;
using MRecipes.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRecipes.Api.Migrations
{
    [DbContext(typeof(MRecipesDbContext))]
    [Migration("20240406101343_UserAdded")]
    partial class UserAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MRecipes.Api.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Article", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 6, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2211),
                            Description = "Ako tak pozerám do kalendára, Veľká noc je už za rohom! Tentokrát mi začiatok roka ubehol ultra rýchlo a človek sa ani nenazdá a bude tu máj a s ním aj ja - opäť o rok staršia. :D Ale nebudem predbiehať, teším sa na Veľkú noc a naše rodinné nedeľné raňajky. Veľkonočnú pasku, hrudku, vajcia natvrdo, údeniny, cviklu s chrenom a zemiakový šalát. Ale nie vždy musí byť Veľká noc len v tradičnom šate. :) Každý rok do nej pridávam aj nejakú tú novinku, naposledy to bola veľkonočná roláda s malinovým krémom, mrkvové mafiny, či avokádová nátierka s granátovým jablkom. A teraz sa môžu moji najbližší tešiť na výborný olivový hummus! Kombinácia cíceru, sezamovej pasty, cesnaku, citrónovej šťavy a olív Kalamata, je výborným krokom na vykročenie do inej svetovej kuchyne. :) Hummus servírovaný s chrumkavou cibuľkou, olivami, kolieskami uhorky a paradajok, pokvapkaný olivovým olejom - u nás doma sa zjedol rýchlosťou blesku a to nie sme milovníci cíceru. Všetky ingrediencie potrebné na tento recept, nájdete pod jednou strechou v Kauflande. Ak ešte nepoznáte ich značku K-Favourites, odporúčam vyskúšať - ingrediencie sú chuťovo výborné a cena príjemná.",
                            Image = "789",
                            Title = "Olivový hummus"
                        },
                        new
                        {
                            Id = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 5, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2223),
                            Description = "Tento víkend sme zvrtli novú variáciu rizota! Pôvodne som chcela spraviť tekvicové, ale z debničky na mňa \"žmurkali\" voňavé cherry paradajky, takže bolo spontánne rozhodnuté v prospech dnešného receptu na paradajkové rizoto. :) Rizoto je jeden z mojich najobľúbenejších receptov, jeho príprava nie je vôbec zložitá, stačí vám naň zopár ingrediencií a dokážete ho pripraviť na desiatky spôsobov v závislosti od sezóny. Na mojom blogu nájdete recept na hubové, ale i cviklové rizoto a čoskoro pribudnú aj ďalšie, keďže vás chcem naňho namotať :) Rizoto je úžasne krémové, prevoňané pečenými paradajkami s cesnakom a čerstvou bazalkou. Čochvíľa nám začne sezóna paradajok, tie skleníkové si však môžete dopriať už dnes a využiť ich rovno pri testovaní tohto receptu, prípadne odporúčam vyskúšať moju rýchlu paradajkovú polievku, paradajkový džem či mäsové guľky v paradajkovej omáčke. Verím, že si pochutíte!",
                            Image = "012",
                            Title = "Famózne paradajkové rizoto"
                        },
                        new
                        {
                            Id = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 4, 3, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2229),
                            Description = "Blíži sa jar a s ňou aj všetky milé stretnutia s našimi blízkymi. U nás doma som zaviedla tradíciu nedeľných dlhých raňajok a vždy keď máme pred sebou voľný víkend, rada na tieto dlhé raňajky pozývam aj svojich najbližších. Jedlo a konverzácie pri spoločnom stole, ktoré ho sprevádzajú, sú pre mňa jedny z najmilších okamihov, preto rada vymýšľam vždy nové a nové kombinácie jedál, ktorými by som ich pohostila. :) A najradšej sa inšpirujem práve v talianskej kuchyni, keďže tá je známa svojou jednoduchosťou, kvalitnými ingredienciami a pritom zaručene chutným výsledkom. Mnohí z vás už určite poznajú recept na chrumkavú paradajkovú bruschettu, ktorú nájdete v mojej prvej kuchárskej knihe. Tento recept je jej malou obmenou, je však vhodný pre všetkých bezlepkáčov, nakoľko v ňom nájdete aj tip na bezgluténové pečivo od Kauflandu. V ich sortimente nájdete pod značkou K-free bezgluténové pečivo a cestoviny, ktoré rada využívam pri príprave bezlepkových receptov. Na chrumkavú bruschettu vám stačí zopár ingrediencií a výsledok je neuveriteľne chutný! Budem sa tešiť, ak recept najbližšie vyskúšate a dáte mi vedieť, ako vám chutilo.",
                            Image = "345",
                            Title = "Chrumkavá paradajková bruschetta"
                        },
                        new
                        {
                            Id = new Guid("4c26d85b-3146-4ed2-9f2c-3993e02ee888"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 30, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2233),
                            Description = "popis",
                            Image = "567",
                            Title = "Zeleninový tart z lístkového cesta"
                        },
                        new
                        {
                            Id = new Guid("2e30dc7c-0c1f-4438-9a3e-3f47792fc82d"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 27, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2237),
                            Description = "popis",
                            Image = "890",
                            Title = "Jednoduchý grécky šalát"
                        },
                        new
                        {
                            Id = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 25, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2240),
                            Description = "popis",
                            Image = "123",
                            Title = "Arašidové brownies s malinami"
                        },
                        new
                        {
                            Id = new Guid("c2902ef3-8e41-4f88-b9a3-31981e4ac220"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 23, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2244),
                            Description = "popis",
                            Image = "456",
                            Title = "Paella s morskými plodmi"
                        },
                        new
                        {
                            Id = new Guid("b5e5d3c7-6b28-456e-87ed-d53c10c3f36d"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 23, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2247),
                            Description = "popis",
                            Image = "787",
                            Title = "Tikka Masala"
                        },
                        new
                        {
                            Id = new Guid("90378085-c0de-4c91-a83c-d216d246b2b1"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 20, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2251),
                            Description = "popis",
                            Image = "011",
                            Title = "Čokoládový tart"
                        },
                        new
                        {
                            Id = new Guid("e62c4460-2829-4f20-b747-5ef468d02d17"),
                            AuthorId = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            DateAdded = new DateTime(2024, 3, 12, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2255),
                            Description = "popis",
                            Image = "341",
                            Title = "Špagety Bolognese"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleComments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10fc697f-bf54-424a-95ac-39222134e86e"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            DateAdded = new DateTime(2024, 4, 4, 12, 13, 43, 272, DateTimeKind.Local).AddTicks(2282),
                            Description = "mnam do pyska",
                            Name = "jozka"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aea952dd-64dc-4e87-848c-07285b405992"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("2a95defa-90fc-440c-b42c-8c7d8e16312c"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            TagId = new Guid("a1b6b079-1c3e-4bb0-8b33-ae6f3dc53e3d")
                        },
                        new
                        {
                            Id = new Guid("66db1dc9-bc79-42e9-98b5-135e95947507"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("d5055ef5-d0b7-4233-bb04-f16283663c8b"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("bef3d572-16b2-43cb-8d17-c481c46d107d"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            TagId = new Guid("b1eac43b-9a2a-4e37-94d2-0a59a493c7d3")
                        },
                        new
                        {
                            Id = new Guid("91c80069-0bbf-43d0-abb4-be0fc743c5d2"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("1948a652-f5f2-41b7-af74-c329b248019b"),
                            ArticleId = new Guid("4c26d85b-3146-4ed2-9f2c-3993e02ee888"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("b351109a-2e45-4295-9b26-20cb513b49af"),
                            ArticleId = new Guid("2e30dc7c-0c1f-4438-9a3e-3f47792fc82d"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("d7302f55-66ad-40ba-93fa-f7eb1e6f8f7f"),
                            ArticleId = new Guid("2e30dc7c-0c1f-4438-9a3e-3f47792fc82d"),
                            TagId = new Guid("c1d698f0-1f87-4c30-9a31-c26e75d99c4f")
                        },
                        new
                        {
                            Id = new Guid("5c135a01-e2fb-4554-9117-1ca26dfda6df"),
                            ArticleId = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            TagId = new Guid("a1f7fd4e-7c7a-4d5b-8a5c-56f5e2d4d18c")
                        },
                        new
                        {
                            Id = new Guid("1795c653-6428-404b-b4a4-c0c66b64b16d"),
                            ArticleId = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("4c30d0d9-e194-4e07-9315-921efa725f79"),
                            ArticleId = new Guid("0860d50a-927f-4d9c-8780-6f8054c20814"),
                            TagId = new Guid("b1f4c4c4-9b64-4aef-9016-4d8a26c44843")
                        },
                        new
                        {
                            Id = new Guid("17cb6e38-c01d-4c3f-8549-2b4bcc2af302"),
                            ArticleId = new Guid("c2902ef3-8e41-4f88-b9a3-31981e4ac220"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("2573f26c-6e6a-4c44-b456-e9df38972792"),
                            ArticleId = new Guid("c2902ef3-8e41-4f88-b9a3-31981e4ac220"),
                            TagId = new Guid("a1b6b079-1c3e-4bb0-8b33-ae6f3dc53e3d")
                        },
                        new
                        {
                            Id = new Guid("09dfc3b0-4f11-41d5-9671-9c8aa8d534ed"),
                            ArticleId = new Guid("b5e5d3c7-6b28-456e-87ed-d53c10c3f36d"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("3f82ecab-79f4-4798-8c46-a5a1bf44b251"),
                            ArticleId = new Guid("b5e5d3c7-6b28-456e-87ed-d53c10c3f36d"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        },
                        new
                        {
                            Id = new Guid("46104c9e-bc3d-4cae-a0c9-8128ebb1a0d7"),
                            ArticleId = new Guid("90378085-c0de-4c91-a83c-d216d246b2b1"),
                            TagId = new Guid("a1f7fd4e-7c7a-4d5b-8a5c-56f5e2d4d18c")
                        },
                        new
                        {
                            Id = new Guid("5f8ee199-8c09-47f1-9251-4b9418be1500"),
                            ArticleId = new Guid("90378085-c0de-4c91-a83c-d216d246b2b1"),
                            TagId = new Guid("b1f4c4c4-9b64-4aef-9016-4d8a26c44843")
                        },
                        new
                        {
                            Id = new Guid("732d4a22-fc49-45cc-8c0d-a4fae74e1d67"),
                            ArticleId = new Guid("e62c4460-2829-4f20-b747-5ef468d02d17"),
                            TagId = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825")
                        },
                        new
                        {
                            Id = new Guid("0876e03a-035e-4072-b2f5-c9439d0b1c39"),
                            ArticleId = new Guid("e62c4460-2829-4f20-b747-5ef468d02d17"),
                            TagId = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5")
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0b3d7e5-c3d6-4f91-914d-877c1b63c1f5"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Ingredient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f30ded7-39f7-4390-9c64-d91f491f0298"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "250 g predvareného cíceru"
                        },
                        new
                        {
                            Id = new Guid("53022b16-3192-4220-91cd-ee2c3ad3a2ce"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "60 g sezamovej pasty"
                        },
                        new
                        {
                            Id = new Guid("86c8cfff-ac8c-4dc6-b335-7168ac4ddef5"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "40 g nakrájaných olív Kalamata (ja som použila olivy Kalamata K-Favourites, ktoré nájdete v Kauflande)"
                        },
                        new
                        {
                            Id = new Guid("3d99bc5e-2904-452b-842b-fdcbd6f6db2d"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "25 ml šťavy z citróna"
                        },
                        new
                        {
                            Id = new Guid("cc8a01bb-ffb3-4822-b0b1-0815796e5cb0"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "1 - 2 strúčiky cesnaku"
                        },
                        new
                        {
                            Id = new Guid("9350253f-fcb2-4bf9-a1f5-5af123233df1"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "2 PL studenej vody'"
                        },
                        new
                        {
                            Id = new Guid("4507734c-c3d7-493f-ab23-b289e61153b9"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "1 PL panenského olivového oleja"
                        },
                        new
                        {
                            Id = new Guid("863ac28e-5398-4876-acc8-68280bdbb6d6"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "1/2 ČL rímskej rasce"
                        },
                        new
                        {
                            Id = new Guid("e11c3dd2-ed4f-4714-a9b6-4890f6cf963a"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "soľ a čierne korenie"
                        },
                        new
                        {
                            Id = new Guid("2f8b125e-7507-4545-a0d9-0d2de15c02c0"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "300 g ryže arborio"
                        },
                        new
                        {
                            Id = new Guid("9b892ffe-51ce-4299-99cd-cb0e91a49657"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "1 cibuľa"
                        },
                        new
                        {
                            Id = new Guid("59e594de-ced4-4cbd-a73d-3d126ed5c04c"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "200 ml bieleho suchého vína"
                        },
                        new
                        {
                            Id = new Guid("5f7804e3-91c9-42a9-9e99-29e09242667a"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "300 ml paradajkového pretlaku/passaty"
                        },
                        new
                        {
                            Id = new Guid("b59e2366-6f66-4a6a-a3a1-512503dce3f3"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "700 ml vývaru/vody"
                        },
                        new
                        {
                            Id = new Guid("9da697e4-5752-4c60-a275-75176ccf1406"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "3 plátky masla"
                        },
                        new
                        {
                            Id = new Guid("bed2cd0e-0d3f-40e7-a420-fb4511a7ad22"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "100 g parmezánu"
                        },
                        new
                        {
                            Id = new Guid("90ed20d1-84fc-4322-8c9c-ff8357e7c7db"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "panenský olivový olej"
                        },
                        new
                        {
                            Id = new Guid("6bfef51d-3533-4db4-9990-880f349949ac"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "soľ a čierne korenie"
                        },
                        new
                        {
                            Id = new Guid("49ff44a4-d03c-4872-bae4-71554cb0d653"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "sušená bazalka"
                        },
                        new
                        {
                            Id = new Guid("4f3bfa91-0c0d-4779-829e-d6e9b4409863"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "sušené oregano"
                        },
                        new
                        {
                            Id = new Guid("cbec752d-0c77-4cf4-b6e3-527d82407a8e"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "hrsť čerstvej bazalky"
                        },
                        new
                        {
                            Id = new Guid("726651a2-4537-4483-9961-b71f4198bc14"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "500 g cherry paradajok"
                        },
                        new
                        {
                            Id = new Guid("791a9472-20b6-4700-acbc-dcf992236b35"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "4 strúčiky cesnaku"
                        },
                        new
                        {
                            Id = new Guid("5d1b5655-c9bf-4848-93cf-b394acc6da7b"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "500 g cherry paradajok"
                        },
                        new
                        {
                            Id = new Guid("e8f4df34-75c0-4ba9-8947-acb02a9f608a"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "7 PL panenského olivového oleja"
                        },
                        new
                        {
                            Id = new Guid("854b5ac1-7ce1-435b-9012-7c90c0afbcaf"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "3 strúčiky cesnaku"
                        },
                        new
                        {
                            Id = new Guid("bf81614e-19d9-4334-a92b-c2eb22a1e5c6"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "1 bageta alebo iné pečivo (pre verziu bez lepku odporúčam použiť 1 balenie bezlepkových svetlých žemlí K-free, ktoré nájdete v Kauflande)"
                        },
                        new
                        {
                            Id = new Guid("ec7fc74a-cecd-4efb-ae50-6f220751b04d"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "mozzarella"
                        },
                        new
                        {
                            Id = new Guid("bc630790-23bd-4a22-bf7c-6a1858678d7a"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "bazalkové pesto"
                        },
                        new
                        {
                            Id = new Guid("bb5b89d7-5834-4c44-92c7-c03b6a926842"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "hrsť lístkov bazalky"
                        },
                        new
                        {
                            Id = new Guid("26172a51-e541-40f2-8b7a-4fc1ed6090f4"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "soľ a čierne korenie"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Step", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df1aaa9b-ae31-44ce-9b41-53010b8651b8"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "Predvarený cícer z konzervy prepláchneme, preložíme do hrnca, zalejeme vodou, jemne osolíme a privedieme do varu. Keď začne vrieť, znížime teplotu a prikrytý varíme približne 20 minút. Mäkký cícer prepláchneme studenou vodou a zbavíme šupiek. Presypeme ho do výkonného mixéra a pridáme k nemu ostatné ingrediencie na hummus. Vymixujeme dohladka a v prípade potreby pridáme trochu vody. Dochutíme soľou, čiernym korením a citrónovou šťavou."
                        },
                        new
                        {
                            Id = new Guid("53705a07-feeb-4ecf-ac40-0afd0f23326b"),
                            ArticleId = new Guid("a2c30491-5461-4e7f-b13d-d1d9d268206f"),
                            Name = "Hummus pred podávaním ochutíme trochou mletej červenej papriky, pokvapkáme olivovým olejom a ozdobíme nakrájanou cibuľou, paradajkami, kolieskami uhorky a hrsťou zelených a čiernych olív. Servírujeme s plátkami citróna, slanými krekrami a výberom rôznych salám a syrov."
                        },
                        new
                        {
                            Id = new Guid("0d847b0d-1e4c-45c8-adb2-22224def78f1"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Paradajky nakrájame na štvrtiny a vložíme do misky. Pokvapkáme ich olivovým olejom (cca 5 PL panenského olivového oleja), pridáme prelisované strúčiky cesnaku a ochutíme soľou a čiernym korením. Premiešame lyžicou a necháme pár minút odležať. Následne celú zmes preložíme na plech vyložený papierom na pečenie a vložíme do rúry vyhriatej na 200 °C. Pečieme 25 minút."
                        },
                        new
                        {
                            Id = new Guid("a091f670-738b-4595-a201-73689dbe9da6"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "V menšom hrnci zohrejeme kurací alebo zeleninový vývar. Ak vývar nemáte, môžete použiť aj vodu - do menšieho hrnca dajte zohriať 700 ml vody a keď bude horúca, pridajte do nej lyžičku soli a dobre premiešajte. Vývar, prípadne vodu zohrievame preto, aby mali podobnú teplotu ako ryža. Vďaka tomu sa nezastaví proces varenia a budete mať rizoto presne také, aké má byť - krémové a neskutočne dobré."
                        },
                        new
                        {
                            Id = new Guid("3fad7a2e-5fca-46b2-8139-0f808e3735fe"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Kým sa vývar/voda zohrieva, zohrejeme si v hlbokej panvici olivový olej, pridáme nadrobno nasekanú cibuľu a opečieme dosklovita. Prisypeme nepremytú ryžu arborio (môžete použiť aj carnaroli ryžu) a poriadne premiešame, aby sa ryža obalila vo vrstve oleja. Opekáme cca 4 minúty, pričom ryžu pravidelne premiešavame. Prilejeme víno a za občasného miešania privedieme do varu. Varíme cca 2 minúty, kým sa víno neodparí."
                        },
                        new
                        {
                            Id = new Guid("9d3b8994-9270-4e29-95ac-fdbc61fe8c97"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Prilejeme paradajkový pretlak/passatu a dobre premiešame. Znížime teplotu na stredný plameň, pridáme naberačku teplého vývaru alebo osolenej vody a pravidelne miešame, kým sa voda nevstrebe. Pokračujeme v postupnom pridávaní vody a zakaždým premiešavame, kým sa voda nevstrebe a ryža sa neuvarí al dente. Ryža je hotová vtedy, keď je obklopená krémovou tekutinou a po ochutnaní je jemne chrumkavá. Celý proces varenia trvá cca 25 minút."
                        },
                        new
                        {
                            Id = new Guid("e97740eb-8fca-44fa-b303-bc976bb8c285"),
                            ArticleId = new Guid("11d5122f-8e94-485a-bf2c-8c432b254cc3"),
                            Name = "Rizoto stiahneme zo sporáka, pridáme k nemu plátky masla a nastrúhaný parmezán a vareškou jemne premiešame. Podľa potreby dochutíme soľou, čiernym korením, trochou sušeného oregana a bazalky. Rizoto servírujeme v hlbokých tanieroch, navrch dáme pečené paradajky a ozdobíme lístkami čerstvej bazalky. Rizoto podávame hneď po uvarení, vtedy chutí najlepšie, s pohárom bieleho vína priam dokonale!"
                        },
                        new
                        {
                            Id = new Guid("943fdffb-a2b1-4a97-9823-12f37759d908"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "Paradajky nakrájame na menšie kúsky a vložíme do misky. Zalejeme ich olivovým olejom, pridáme prelisované strúčiky cesnaku, ochutíme soľou a čiernym korením a dobre premiešame. Necháme pár minút postáť. Následne paradajky preložíme na plech vyložený papierom na pečenie a vložíme do rúry vyhriatej na 200 °C. Pečieme približne 30 minút, kým nezmäknú."
                        },
                        new
                        {
                            Id = new Guid("c34151f9-1f9d-49f8-a060-faf7901312f1"),
                            ArticleId = new Guid("b83ebc52-d646-4ab1-94df-72582f0d8c5a"),
                            Name = "Bagetu alebo iné pečivo nakrájame na približne rovnaké kúsky. Ak použijete bezlepkové svetlé žemle K-free od Kauflandu, prekrojte ich na polovicu. Jednotlivé kúsky potrieme zvyšným olivovým olejom, ktorý zostal v miske a opečieme na grile, panvici alebo vložíme na 10 minút do rúry. Chrumkavé pečivo potrieme pestom, na to dáme plátok mozzarelly, grilované paradajky a lístky čerstvej bazalky."
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ee5d1b8-08e5-43e5-bdc9-28dc607e5825"),
                            Name = "Hlavný chod"
                        },
                        new
                        {
                            Id = new Guid("a1f7fd4e-7c7a-4d5b-8a5c-56f5e2d4d18c"),
                            Name = "Dezerty"
                        },
                        new
                        {
                            Id = new Guid("b1eac43b-9a2a-4e37-94d2-0a59a493c7d3"),
                            Name = "Predjedlá"
                        },
                        new
                        {
                            Id = new Guid("c1d698f0-1f87-4c30-9a31-c26e75d99c4f"),
                            Name = "Šaláty"
                        },
                        new
                        {
                            Id = new Guid("d1e13f16-9e32-4d3e-8302-28516d982aef"),
                            Name = "Polievky"
                        },
                        new
                        {
                            Id = new Guid("e13e2d0d-c51f-4fa9-97cb-4e6c018474cb"),
                            Name = "Nápoje"
                        },
                        new
                        {
                            Id = new Guid("f1db63a1-21f1-49c4-8f0c-208e1f4a8ff5"),
                            Name = "Bez lepku"
                        },
                        new
                        {
                            Id = new Guid("a1b6b079-1c3e-4bb0-8b33-ae6f3dc53e3d"),
                            Name = "Bez laktózy"
                        },
                        new
                        {
                            Id = new Guid("b1f4c4c4-9b64-4aef-9016-4d8a26c44843"),
                            Name = "Sladké"
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6105e9f8-da03-400b-a703-28dbafd9a95d"),
                            BirthDate = new DateOnly(2004, 4, 6),
                            Email = "user@gmail.com",
                            Name = "JustUser",
                            Password = "pw",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("0c754691-fff0-4738-82dc-f9c4daffeadd"),
                            BirthDate = new DateOnly(1994, 4, 6),
                            Email = "admin@gmail.com",
                            Name = "JustAdmin",
                            Password = "admin",
                            Role = 0
                        });
                });

            modelBuilder.Entity("MRecipes.Api.Models.Article", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleComment", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MRecipes.Api.Models.ArticleTag", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MRecipes.Api.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Ingredient", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Ingredients")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Step", b =>
                {
                    b.HasOne("MRecipes.Api.Models.Article", "Article")
                        .WithMany("Steps")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MRecipes.Api.Models.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
